name: yaepub
description: Yet Another epub parser
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.11.0-93.1.beta

dependencies:
  collection: any
  path: any
  crypto: any
  xml: any
  archive: any
  mime_type: any

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
