name: yaepub
description: "yet another epub parser"
version: 0.0.1

environment:
  sdk: ^3.11.0-93.1.beta
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: any
  path: any
  xml: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


